"""
CryptoStream AI — Airflow DAG: Parquet Data Lake to Google BigQuery
========================================================================
DAG ID   : datalake_to_bigquery
Schedule : 02:00 AM daily (runs after daily_aggregation_dag)
Purpose  : Uploads the local cold storage (Parquet files) generated by
           lake-writer for the previous day into Google Cloud Storage (GCS),
           then loads them into the BigQuery analytical data warehouse.

Architecture (Multi-persona):
    - Supports Data Analysts utilizing BigQuery for heavy OLAP scanning.
    - Forms the presentation layer foundation for Looker Studio dashboards.

Note on DRY RUN:
    By default, DRY_RUN=True. This allows the DAG to scan for files and
    print what it *would* do without requiring an active GCP JSON key.
    To connect to real GCP infrastructure, set DRY_RUN=False and configure
    the 'google_cloud_default' connection in Airflow.
"""

from __future__ import annotations

import logging
import os
import glob
from datetime import datetime, timedelta

from airflow.models import Variable

from airflow import DAG
from airflow.operators.python import PythonOperator, ShortCircuitOperator
from airflow.operators.dummy import DummyOperator
from airflow.utils.task_group import TaskGroup

try:
    from airflow.providers.google.cloud.transfers.local_to_gcs import LocalFilesystemToGCSOperator
    from airflow.providers.google.cloud.transfers.gcs_to_bigquery import GCSToBigQueryOperator
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateEmptyDatasetOperator
    GCP_PROVIDERS_AVAILABLE = True
except ImportError:
    GCP_PROVIDERS_AVAILABLE = False


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DRY_RUN = False  # Set to False to actually push to Google Cloud

GCP_CONN_ID = 'google_cloud_default'
# Reads from Airflow Variable; falls back to 'crypto-stream-lake-01' if not set
GCS_BUCKET = Variable.get('gcs_bucket_name', default_var='crypto-stream-lake-01')
BQ_DATASET = 'crypto_stream'
BQ_TABLE = 'raw_trades'

LOCAL_DATALAKE_ROOT = '/opt/datalake'

DEFAULT_ARGS = {
    'owner': 'data-engineering-team',
    'depends_on_past': False,
    'email_on_failure': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Python Callables
# ---------------------------------------------------------------------------

def _get_target_path(logical_date) -> str:
    """Returns the expected partitioned path for the target date."""
    year = logical_date.strftime("%Y")
    month = logical_date.strftime("%m")
    day = logical_date.strftime("%d")
    return os.path.join(LOCAL_DATALAKE_ROOT, f"year={year}", f"month={month}", f"day={day}")

def scan_parquet_files(**context) -> bool:
    """Checks if there are Parquet files and stores their paths for uploading."""
    logical_date = context['data_interval_start'].date()
    target_path = _get_target_path(logical_date)
    
    log.info(f"Checking for data in Partition path: {target_path}")
    
    files = []
    if os.path.exists(target_path):
        files = glob.glob(os.path.join(target_path, "**/*.parquet"), recursive=True)

    # Greedy Mode: If specific day is empty, look everywhere in datalake
    if not files:
        log.info(f"Partition path empty. Searching all of {LOCAL_DATALAKE_ROOT} recursively...")
        # Use recursive glob to find all parquet files anywhere in the datalake volume
        files = glob.glob(os.path.join(LOCAL_DATALAKE_ROOT, "**/*.parquet"), recursive=True)
    
    if not files:
        # Final check: sometimes the root has files directy (non-recursive)
        files = glob.glob(os.path.join(LOCAL_DATALAKE_ROOT, "*.parquet"))
    
    if not files:
        log.warning(f"No parquet files found in {LOCAL_DATALAKE_ROOT}. Skipping.")
        return False
        
    log.info(f"SUCCESS: Found {len(files)} parquet files to process.")
    
    # Store results for downstream tasks
    context['ti'].xcom_push(key='parquet_files', value=files)
    return True

def upload_files_to_gcs(**context):
    """Effectively uploads a list of local files to GCS bucket."""
    from airflow.providers.google.cloud.hooks.gcs import GCSHook
    
    files = context['ti'].xcom_pull(task_ids='check_data_availability', key='parquet_files')
    target_date = context['data_interval_start'].date()
    hook = GCSHook(gcp_conn_id=GCP_CONN_ID)
    
    log.info(f"Uploading {len(files)} files to gs://{GCS_BUCKET}/raw_trades/{target_date}/")
    
    for f in files:
        file_name = os.path.basename(f)
        destination_path = f"raw_trades/{target_date}/{file_name}"
        hook.upload(
            bucket_name=GCS_BUCKET,
            object_name=destination_path,
            filename=f
        )
        log.info(f"  -> Uploaded: {file_name}")

def dry_run_bq_load(**context):
    """Simulates loading files from GCS to BigQuery."""
    target_date = context['data_interval_start'].date()
    log.info(f"[DRY RUN] Loading gs://{GCS_BUCKET}/raw_trades/{target_date}/*.parquet into {BQ_DATASET}.{BQ_TABLE}")


# ---------------------------------------------------------------------------
# DAG Definition
# ---------------------------------------------------------------------------
with DAG(
    dag_id='datalake_to_bigquery',
    description='Uploads cold storage Parquet trades to BigQuery for Analysts',
    default_args=DEFAULT_ARGS,
    start_date=datetime(2026, 1, 1),
    schedule_interval='0 2 * * *',
    catchup=False,
    tags=['crypto', 'datalake', 'gcp', 'bigquery', 'phase-7'],
) as dag:

    t_check = ShortCircuitOperator(
        task_id='check_data_availability',
        python_callable=scan_parquet_files,
        provide_context=True,
    )

    if DRY_RUN or not GCP_PROVIDERS_AVAILABLE:
        t_upload = PythonOperator(
            task_id='upload_to_gcs',
            python_callable=lambda **c: log.info("DRY RUN: Uploading files..."),
            provide_context=True,
        )
        t_create_ds = DummyOperator(task_id='create_dataset')
        t_load = PythonOperator(
            task_id='gcs_to_bigquery',
            python_callable=dry_run_bq_load,
            provide_context=True,
        )
    else:
        t_upload = PythonOperator(
            task_id='upload_to_gcs',
            python_callable=upload_files_to_gcs,
            provide_context=True,
        )
        
        t_create_ds = BigQueryCreateEmptyDatasetOperator(
            task_id='create_dataset',
            dataset_id=BQ_DATASET,
            location='asia-southeast1',
            gcp_conn_id=GCP_CONN_ID,
            if_exists='ignore',
        )
        
        t_load = GCSToBigQueryOperator(
            task_id='gcs_to_bigquery',
            bucket=GCS_BUCKET,
            source_objects=[f"raw_trades/{{{{ data_interval_start.strftime('%Y-%m-%d') }}}}/*.parquet"],
            destination_project_dataset_table=f"{BQ_DATASET}.{BQ_TABLE}",
            source_format='PARQUET',
            write_disposition='WRITE_APPEND',
            location='asia-southeast1',
            gcp_conn_id=GCP_CONN_ID,
        )

    t_done = DummyOperator(task_id='upload_complete')

    t_check >> t_upload >> t_create_ds >> t_load >> t_done
